import { useState } from 'react';
import { useMutation, useQueryClient } from '@tanstack/react-query';
import { supabase } from '@/integrations/supabase/client';
import { useToast } from '@/hooks/use-toast';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Loader2, UserPlus } from 'lucide-react';
import { z } from 'zod';

const memberSchema = z.object({
  nome: z.string().min(1, 'Nome obrigatório').max(255),
  telefone: z.string().min(9, 'Telefone inválido').max(20),
  email: z.string().email('Email inválido').optional().or(z.literal('')),
});

interface QuickMemberModalProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
  onSuccess?: (member: { id: string; nome: string; telefone: string; qr_code: string }) => void;
}

const QuickMemberModal = ({ open, onOpenChange, onSuccess }: QuickMemberModalProps) => {
  const { toast } = useToast();
  const queryClient = useQueryClient();

  const [formData, setFormData] = useState({
    nome: '',
    telefone: '',
    email: '',
  });

  const createMutation = useMutation({
    mutationFn: async (data: { nome: string; telefone: string; email: string }) => {
      const { data: newMember, error } = await supabase
        .from('members')
        .insert({
          nome: data.nome,
          telefone: data.telefone,
          email: data.email || null,
          qr_code: '', // Will be auto-generated by trigger
        })
        .select()
        .single();
      if (error) throw error;
      return newMember;
    },
    onSuccess: (data) => {
      queryClient.invalidateQueries({ queryKey: ['members'] });
      toast({ title: 'Membro criado com sucesso' });
      setFormData({ nome: '', telefone: '', email: '' });
      onOpenChange(false);
      onSuccess?.(data);
    },
    onError: (error) => {
      console.error('Error creating member:', error);
      toast({ title: 'Erro ao criar membro', variant: 'destructive' });
    },
  });

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();

    const validation = memberSchema.safeParse(formData);
    if (!validation.success) {
      toast({
        title: 'Erro de validação',
        description: validation.error.errors[0].message,
        variant: 'destructive',
      });
      return;
    }

    createMutation.mutate(formData);
  };

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle className="uppercase tracking-wider flex items-center gap-2">
            <UserPlus className="h-5 w-5" />
            Cadastro Rápido
          </DialogTitle>
          <DialogDescription>
            Cadastre um novo membro rapidamente
          </DialogDescription>
        </DialogHeader>

        <form onSubmit={handleSubmit} className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="quick-nome">Nome *</Label>
            <Input
              id="quick-nome"
              value={formData.nome}
              onChange={(e) => setFormData({ ...formData, nome: e.target.value })}
              className="bg-secondary border-border"
              placeholder="Nome completo"
              required
              autoFocus
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="quick-telefone">Telefone *</Label>
            <Input
              id="quick-telefone"
              value={formData.telefone}
              onChange={(e) => setFormData({ ...formData, telefone: e.target.value })}
              className="bg-secondary border-border"
              placeholder="+351 912 345 678"
              required
            />
          </div>

          <div className="space-y-2">
            <Label htmlFor="quick-email">Email (opcional)</Label>
            <Input
              id="quick-email"
              type="email"
              value={formData.email}
              onChange={(e) => setFormData({ ...formData, email: e.target.value })}
              className="bg-secondary border-border"
              placeholder="email@exemplo.com"
            />
          </div>

          <div className="flex gap-2 pt-2">
            <Button
              type="button"
              variant="outline"
              className="flex-1"
              onClick={() => onOpenChange(false)}
            >
              Cancelar
            </Button>
            <Button
              type="submit"
              className="flex-1 bg-accent hover:bg-accent/90"
              disabled={createMutation.isPending}
            >
              {createMutation.isPending && <Loader2 className="h-4 w-4 mr-2 animate-spin" />}
              Cadastrar
            </Button>
          </div>
        </form>
      </DialogContent>
    </Dialog>
  );
};

export default QuickMemberModal;
